services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./letsencrypt:/etc/letsencrypt
            - ./nginx_vhost:/etc/nginx/conf.d
            - ./www:/var/www/html
        depends_on:
            - certbot
            - frontend
            - backend
        networks:
            - app-network

    certbot:
        image: certbot/certbot
        container_name: certbot
        depends_on:
            - nginx
        volumes:
            - ./letsencrypt:/etc/letsencrypt
            - ./www:/var/www/html
        command: certonly --webroot --webroot-path=/var/www/html --email stepanpavlovsky@mail.com --agree-tos --no-eff-email -d test.world-itech.ru

    frontend:
        build:
            context: ./frontend
        ports:
            - '3000:80'
        depends_on:
            - backend
        networks:
            - app-network

    backend:
        build:
            context: ./backend
        ports:
            - '5000:5000'
        environment:
            PORT: 5000
            POSTGRES_USER: postgres
            POSTGRES_DB: DockerTEST
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        secrets:
            - db_password
        depends_on:
            - postgres
        networks:
            - app-network

    postgres:
        image: postgres:15
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: DockerTEST
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
        ports:
            - '5433:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init-scripts:/docker-entrypoint-initdb.d
        secrets:
            - db_password
        networks:
            - app-network

secrets:
    db_password:
        file: ./db_password.txt

volumes:
    postgres_data:
    letsencrypt:
    www:

networks:
    app-network:
        driver: bridge
